### ISSUE TITLE
can't read xlsx file Download.xlsx

### ISSUE THREAD

**Issue by kintaro1981** [frankIT/ofxstatement-fineco#10]
Hello,

I don't know if is because of this: https://github.com/frankIT/ofxstatement-fineco/issues/8
(but I don't think so as I already tried to manually overwrite fineco.py with the latest one)

If I try to convert the saving statement it replies with this:
```
MacBook-Pro-di-xxx:~ xxx$ ofxstatement convert -t fineco ./Downloads/Download.xlsx ./Downloads/Download.ofx
Traceback (most recent call last):
  File "/usr/local/bin/ofxstatement", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.9/site-packages/ofxstatement/tool.py", line 195, in run
    return args.func(args)
  File "/usr/local/lib/python3.9/site-packages/ofxstatement/tool.py", line 166, in convert
    statement = parser.parse()
  File "/usr/local/lib/python3.9/site-packages/ofxstatement/plugins/fineco.py", line 85, in parse
    workbook = xlrd.open_workbook(self.filename)
  File "/usr/local/lib/python3.9/site-packages/xlrd/__init__.py", line 170, in open_workbook
    raise XLRDError(FILE_FORMAT_DESCRIPTIONS[file_format]+'; not supported')
xlrd.biffh.XLRDError: Excel xlsx file; not supported
```

**Comment by frankIT** [comment]
I noticed in the issue you mentioned that you're using [xlrd-2.0.1](https://pypi.org/project/xlrd/2.0.1/), that apparently dropped the support for the xlsx files that it has back in [1.2.0](https://pypi.org/project/xlrd/1.2.0/). Long story short: i reckon i'll have to swap to [openpyxl](https://pypi.org/project/openpyxl/). As a temp workaround you might wanna give a shot to downgrade it with smth like: `pip3 install xlrd==1.2.0`

**Comment by kintaro1981** [comment]
`pip3 install xlrd==1.2.0` worked
